from sqlalchemy import and_
from models import db
from models.employee import Employee
from models.wage_master import WageMaster
from models.account_details import AccountDetails
from models.site import Site
from datetime import datetime

def create_employee(payload: dict) -> Employee:
    # Get salary code from payload or create if wage master details are provided
    salary_code = payload.get("salary_code")
    if not salary_code and all(k in payload for k in ("site_name", "rank", "state", "base_salary")):
        salary_code = _get_or_create_wage_master(
            payload.get("site_name"),
            payload.get("rank"),
            payload.get("state"),
            payload.get("base_salary"),
            payload.get("skill_level", "Skilled")
        )

    # Parse date fields
    date_of_birth = _parse_date(payload.get("date_of_birth"))
    hire_date = _parse_date(payload.get("hire_date") or payload.get("date_of_joining"))

    emp = Employee(
        # Note: employee_id will be auto-generated by the sequence
        first_name=payload.get("first_name", ""),
        last_name=payload.get("last_name", ""),
        father_name=payload.get("father_name"),
        address=payload.get("address"),
        adhar_number=payload.get("adhar_number") or payload.get("aadhaar_number"),
        place_of_birth=payload.get("place_of_birth"),
        marital_status=payload.get("marital_status"),
        date_of_birth=date_of_birth,
        email=payload.get("email"),
        phone_number=payload.get("phone_number") or payload.get("mobile_number"),
        hire_date=hire_date,
        job_title=payload.get("job_title") or payload.get("designation"),
        family_details=payload.get("family_details"),
        department_id=payload.get("department_id") or payload.get("department"),
        employment_status=payload.get("employment_status", "Active"),
        gender=payload.get("gender"),
        nationality=payload.get("nationality", "Indian"),
        blood_group=payload.get("blood_group"),
        alternate_contact_number=payload.get("alternate_contact_number"),
        pan_card_number=payload.get("pan_card_number"),
        voter_id_driving_license=payload.get("voter_id_driving_license"),
        uan=payload.get("uan"),
        esic_number=payload.get("esic_number"),
        employment_type=payload.get("employment_type"),
        designation=payload.get("designation"),
        work_location=payload.get("work_location"),
        reporting_manager=payload.get("reporting_manager"),
        base_salary=payload.get("base_salary"),
        skill_category=payload.get("skill_category"),
        wage_rate=payload.get("wage_rate"),
        pf_applicability=bool(payload.get("pf_applicability", False)),
        esic_applicability=bool(payload.get("esic_applicability", False)),
        professional_tax_applicability=bool(payload.get("professional_tax_applicability", False)),
        salary_advance_loan=payload.get("salary_advance_loan"),
        highest_qualification=payload.get("highest_qualification"),
        year_of_passing=payload.get("year_of_passing"),
        additional_certifications=payload.get("additional_certifications"),
        experience_duration=payload.get("experience_duration"),
        emergency_contact_name=payload.get("emergency_contact_name"),
        emergency_contact_relationship=payload.get("emergency_contact_relationship"),
        emergency_contact_phone=payload.get("emergency_contact_phone"),
        salary_code=salary_code,
        site_id=payload.get("site_id"),
        created_by=payload.get("created_by", "system")
    )

    db.session.add(emp)
    db.session.flush()  # Get the auto-generated employee ID

    # Create account details if bank information is provided
    if payload.get("bank_account_number") and payload.get("ifsc_code"):
        account_details = AccountDetails(
            emp_id=emp.employee_id,
            account_number=payload.get("bank_account_number"),
            ifsc_code=payload.get("ifsc_code"),
            bank_name=payload.get("bank_name"),
            branch_name=payload.get("branch_name"),
            created_by=payload.get("created_by", "system")
        )
        db.session.add(account_details)

    db.session.commit()
    return emp

def _get_or_create_wage_master(site_name: str, rank: str, state: str, base_salary, skill_level="Skilled"):
    # Exact match
    wm = WageMaster.query.filter_by(site_name=site_name, rank=rank, state=state, is_active=True).first()
    if wm:
        return wm.salary_code

    # Fallback: first 3 characters match for site_name
    prefix = (site_name or "")[:3]
    wm = WageMaster.query.filter(
        WageMaster.rank == rank,
        WageMaster.state == state,
        WageMaster.site_name.ilike(f"{prefix}%"),
        WageMaster.is_active == True
    ).first()
    if wm:
        return wm.salary_code

    # Generate salary code
    salary_code = _generate_salary_code(site_name, rank, state)

    # Create new
    wm = WageMaster(
        salary_code=salary_code,
        site_name=site_name,
        rank=rank,
        state=state,
        base_wage=base_salary or 0,
        skill_level=skill_level
    )
    db.session.add(wm)
    db.session.flush()  # get wm.id
    return wm.salary_code

def _generate_salary_code(site_name: str, rank: str, state: str) -> str:
    """Generate salary code from site name, rank, and state"""
    import re

    # Clean and format inputs
    site_clean = re.sub(r'[^a-zA-Z]', '', site_name.upper())
    rank_clean = re.sub(r'[^a-zA-Z]', '', rank.upper())
    state_clean = re.sub(r'[^a-zA-Z]', '', state.upper())

    # Extract site prefix (first 3 characters)
    site_prefix = site_clean[:3] if len(site_clean) >= 3 else site_clean

    # Basic code format
    base_code = f"{site_prefix}{rank_clean}{state_clean}"

    # Check if code already exists
    existing_code = WageMaster.query.filter(WageMaster.salary_code == base_code).first()

    if not existing_code:
        return base_code

    # If exists, add a numeric suffix
    counter = 1
    while True:
        new_code = f"{base_code}{counter:02d}"
        existing = WageMaster.query.filter(WageMaster.salary_code == new_code).first()
        if not existing:
            return new_code
        counter += 1

def _parse_date(date_str):
    """Parse date string to date object"""
    if not date_str:
        return None

    if isinstance(date_str, datetime):
        return date_str.date()

    # Try different date formats
    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%m/%d/%Y"):
        try:
            return datetime.strptime(str(date_str), fmt).date()
        except ValueError:
            continue

    return None

def _parse_bool(value):
    """Parse boolean value from various formats"""
    if value is None or pd_isna(value):
        return False
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() in ('true', 'yes', '1', 'y')
    if isinstance(value, (int, float)):
        return value != 0
    return False

def _get_site_id_from_name(site_name):
    """Get site_id from site_name"""
    if not site_name:
        return None
    site = Site.query.filter_by(site_name=site_name, is_active=True).first()
    return site.site_id if site else None

def _get_site_name_from_work_location(work_location):
    """Try to extract or map site_name from work_location"""
    if not work_location:
        return None
    
    # First try exact match
    site = Site.query.filter_by(site_name=work_location, is_active=True).first()
    if site:
        return work_location
    
    # Try partial match (case insensitive)
    site = Site.query.filter(Site.site_name.ilike(f"%{work_location}%"), Site.is_active == True).first()
    if site:
        return site.site_name
    
    # If no match found, return the work_location as is (might need manual mapping)
    return work_location

def bulk_import_from_frames(sheet_frames: dict) -> dict:
    """
    sheet_frames: dict {sheet_name: DataFrame}
    Returns a summary: {"inserted": n, "errors": [row_error, ...]}
    """
    from utils.excel_parser import detect_excel_format

    summary = {"inserted": 0, "errors": []}

    for sheet, df in sheet_frames.items():
        # Detect format for this sheet
        format_type = detect_excel_format(df)

        for idx, row in df.iterrows():
            try:
                # Split full name into first and last name
                full_name = str(row["Full Name"]).strip()
                name_parts = full_name.split(" ", 1)
                first_name = name_parts[0] if name_parts else ""
                last_name = name_parts[1] if len(name_parts) > 1 else ""

                if format_type == 'old':
                    # Old format payload
                    site_name = str(row["Site Name"]).strip() if "Site Name" in row and not pd_isna(row["Site Name"]) else None
                    payload = {
                        "first_name": first_name,
                        "last_name": last_name,
                        "date_of_birth": pd_to_date(row["Date of Birth"]),
                        "gender": str(row["Gender"]).strip() if not pd_isna(row["Gender"]) else None,
                        "site_name": site_name,
                        "rank": str(row["Rank"]).strip() if "Rank" in row and not pd_isna(row["Rank"]) else None,
                        "state": str(row["State"]).strip() if "State" in row and not pd_isna(row["State"]) else None,
                        "base_salary": row["Base Salary"] if "Base Salary" in row and not pd_isna(row["Base Salary"]) else None,
                    }
                    # Add site_id for employee record
                    if site_name:
                        payload["site_id"] = _get_site_id_from_name(site_name)
                else:
                    # New format payload (comprehensive)
                    work_location = str(row.get("Work Location")).strip() if row.get("Work Location") and not pd_isna(row["Work Location"]) else None
                    
                    payload = {
                        "first_name": first_name,
                        "last_name": last_name,
                        "date_of_birth": pd_to_date(row.get("Date of Birth")),
                        "gender": str(row.get("Gender")).strip() if row.get("Gender") and not pd_isna(row["Gender"]) else None,
                        "marital_status": str(row.get("Marital Status")).strip() if row.get("Marital Status") and not pd_isna(row["Marital Status"]) else None,
                        "nationality": str(row.get("Nationality")).strip() if row.get("Nationality") and not pd_isna(row["Nationality"]) else "Indian",
                        "blood_group": str(row.get("Blood Group")).strip() if row.get("Blood Group") and not pd_isna(row["Blood Group"]) else None,
                        "address": str(row.get("Permanent Address")).strip() if row.get("Permanent Address") and not pd_isna(row["Permanent Address"]) else None,
                        "phone_number": str(row.get("Mobile Number")).strip() if row.get("Mobile Number") and not pd_isna(row["Mobile Number"]) else None,
                        "alternate_contact_number": str(row.get("Alternate Contact Number")).strip() if row.get("Alternate Contact Number") and not pd_isna(row["Alternate Contact Number"]) else None,
                        "adhar_number": str(row.get("Aadhaar Number")).strip() if row.get("Aadhaar Number") and not pd_isna(row["Aadhaar Number"]) else None,
                        "pan_card_number": str(row.get("PAN Card Number")).strip() if row.get("PAN Card Number") and not pd_isna(row["PAN Card Number"]) else None,
                        "voter_id_driving_license": str(row.get("Voter ID / Driving License")).strip() if row.get("Voter ID / Driving License") and not pd_isna(row["Voter ID / Driving License"]) else None,
                        "uan": str(row.get("UAN")).strip() if row.get("UAN") and not pd_isna(row["UAN"]) else None,
                        "esic_number": str(row.get("ESIC Number")).strip() if row.get("ESIC Number") and not pd_isna(row["ESIC Number"]) else None,
                        "hire_date": pd_to_date(row.get("Date of Joining")),
                        "employment_type": str(row.get("Employment Type")).strip() if row.get("Employment Type") and not pd_isna(row["Employment Type"]) else None,
                        "department_id": str(row.get("Department")).strip() if row.get("Department") and not pd_isna(row["Department"]) else None,
                        "designation": str(row.get("Designation")).strip() if row.get("Designation") and not pd_isna(row["Designation"]) else None,
                        "work_location": work_location,
                        "reporting_manager": str(row.get("Reporting Manager")).strip() if row.get("Reporting Manager") and not pd_isna(row["Reporting Manager"]) else None,
                        "skill_category": str(row.get("Skill Category")).strip() if row.get("Skill Category") and not pd_isna(row["Skill Category"]) else None,
                        "salary_advance_loan": str(row.get("Salary Advance/Loan")).strip() if row.get("Salary Advance/Loan") and not pd_isna(row["Salary Advance/Loan"]) else None,
                        "pf_applicability": _parse_bool(row.get("PF Applicability")),
                        "esic_applicability": _parse_bool(row.get("ESIC Applicability")),
                        "professional_tax_applicability": _parse_bool(row.get("Professional Tax Applicability")),
                        "experience_duration": str(row.get("Experience Duration")).strip() if row.get("Experience Duration") and not pd_isna(row["Experience Duration"]) else None,
                        "highest_qualification": str(row.get("Highest Qualification")).strip() if row.get("Highest Qualification") and not pd_isna(row["Highest Qualification"]) else None,
                        "year_of_passing": str(row.get("Year of Passing")).strip() if row.get("Year of Passing") and not pd_isna(row["Year of Passing"]) else None,
                        "additional_certifications": str(row.get("Additional Certifications")).strip() if row.get("Additional Certifications") and not pd_isna(row["Additional Certifications"]) else None,
                        "emergency_contact_name": str(row.get("Emergency Contact Name")).strip() if row.get("Emergency Contact Name") and not pd_isna(row["Emergency Contact Name"]) else None,
                        "emergency_contact_relationship": str(row.get("Emergency Relationship")).strip() if row.get("Emergency Relationship") and not pd_isna(row["Emergency Relationship"]) else None,
                        "emergency_contact_phone": str(row.get("Emergency Phone Number")).strip() if row.get("Emergency Phone Number") and not pd_isna(row["Emergency Phone Number"]) else None,
                        "salary_code": str(row.get("Salary Code")).strip() if row.get("Salary Code") and not pd_isna(row["Salary Code"]) else None,
                        "bank_account_number": str(row.get("Bank Account Number")).strip() if row.get("Bank Account Number") and not pd_isna(row["Bank Account Number"]) else None,
                        "bank_name": str(row.get("Bank Name")).strip() if row.get("Bank Name") and not pd_isna(row["Bank Name"]) else None,
                        "ifsc_code": str(row.get("IFSC Code")).strip() if row.get("IFSC Code") and not pd_isna(row["IFSC Code"]) else None,
                    }
                    
                    # For new format, try to map work_location to site_id
                    if work_location:
                        site_name = _get_site_name_from_work_location(work_location)
                        if site_name:
                            payload["site_id"] = _get_site_id_from_name(site_name)

                if not payload["first_name"]:
                    raise ValueError("First Name is required")

                # create
                _ = create_employee(payload)
                summary["inserted"] += 1
            except Exception as e:
                summary["errors"].append(
                    {"sheet": sheet, "row_index": int(idx), "error": str(e)}
                )

    return summary

# Helpers for date coercion without importing pandas here
from datetime import datetime
def pd_isna(v):
    try:
        import pandas as pd
        return pd.isna(v)
    except Exception:
        return v is None

def pd_to_date(v):
    if v is None or pd_isna(v) or str(v).strip() == "":
        return None
    if isinstance(v, datetime):
        return v.date()
    # try to parse common formats
    for fmt in ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%m/%d/%Y"):
        try:
            return datetime.strptime(str(v), fmt).date()
        except ValueError:
            continue
    # excel serial number?
    try:
        import pandas as pd
        if isinstance(v, (int, float)):
            return pd.to_datetime(v, unit="D", origin="1899-12-30").date()
    except Exception:
        pass
    # last resort
    try:
        return datetime.fromisoformat(str(v)).date()
    except Exception:
        return None

def get_employee_by_id(employee_id: int) -> Employee:
    """Get employee by employee ID"""
    return Employee.query.filter_by(employee_id=employee_id).first()

def get_all_employees(page: int = 1, per_page: int = 10):
    """Get all employees with pagination"""
    return Employee.query.paginate(
        page=page,
        per_page=per_page,
        error_out=False
    )

def get_all_employees_unpaginated():
    """Get all employees without pagination"""
    return Employee.query.order_by(Employee.employee_id.asc()).all()

def search_employees(search_term: str = "", department: str = None, employment_status: str = None):
    """Search employees by various criteria"""
    query = Employee.query

    if search_term:
        search_filter = f"%{search_term}%"
        query = query.filter(
            db.or_(
                Employee.first_name.ilike(search_filter),
                Employee.last_name.ilike(search_filter),
                Employee.employee_id.cast(db.String).ilike(search_filter),
                Employee.email.ilike(search_filter)
            )
        )

    if department:
        query = query.filter(Employee.department_id == department)

    if employment_status:
        query = query.filter(Employee.employment_status == employment_status)

    return query.order_by(Employee.employee_id.asc()).all()

# Helper function to get the next employee ID (for reference or debugging)
def get_next_employee_id() -> int:
    """
    Get the next employee ID that would be generated by the sequence.
    This is mainly for reference/debugging purposes since the sequence handles it automatically.
    """
    result = db.session.execute("SELECT nextval('employee_id_seq')")
    next_id = result.scalar()
    # Rollback to not consume the sequence value
    db.session.rollback()
    return next_id

def reset_employee_id_sequence(start_value: int = 91510001):
    """
    Reset the employee ID sequence to a specific starting value.
    Use with caution - only for initialization or data migration.
    """
    db.session.execute(f"ALTER SEQUENCE employee_id_seq RESTART WITH {start_value}")
    db.session.commit()