"""initial schema

Revision ID: 20f3ff863cbd
Revises: 
Create Date: 2025-08-24 10:44:02.544742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f3ff863cbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wage_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_code', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('base_wage', sa.Float(), nullable=False),
    sa.Column('skill_level', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wage_masters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wage_masters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wage_masters_salary_code'), ['salary_code'], unique=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'wage_masters', ['salary_code'], ['salary_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('wage_masters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wage_masters_salary_code'))
        batch_op.drop_index(batch_op.f('ix_wage_masters_id'))

    op.drop_table('wage_masters')
    # ### end Alembic commands ###
