"""Add site_name column to wage_masters

Revision ID: 4581e2ee5d10
Revises: 20f3ff863cbd
Create Date: 2025-08-24 15:24:32.706558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4581e2ee5d10'
down_revision = '20f3ff863cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('wage_masters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('wage_masters_site_id_fkey'), type_='foreignkey')
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_masters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('wage_masters_site_id_fkey'), 'sites', ['site_id'], ['site_id'])
        batch_op.drop_column('site_name')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
