"""Add Something

Revision ID: 850d1426a580
Revises: c8bbc8af1979
Create Date: 2025-08-25 13:34:01.923004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850d1426a580'
down_revision = 'c8bbc8af1979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
