"""Fix deductions table employee_id type

Revision ID: 9d25b2d4dd3e
Revises: 850d1426a580
Create Date: 2025-08-25 22:46:10.582486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d25b2d4dd3e'
down_revision = '850d1426a580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deductions',
    sa.Column('deduction_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('deduction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deductions')
    # ### end Alembic commands ###
