"""Add attendance performance indexes

Revision ID: e4ee963a6f4c
Revises: d3d199411431
Create Date: 2025-09-22 18:33:33.795738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ee963a6f4c'
down_revision = 'd3d199411431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attendance_date'))
        batch_op.drop_index(batch_op.f('idx_attendance_employee'))
        batch_op.drop_index(batch_op.f('idx_attendance_employee_date'))
        batch_op.drop_index(batch_op.f('idx_attendance_status'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_employee_employee_id'))
        batch_op.drop_index(batch_op.f('idx_employee_site_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_employee_site_id'), ['site_id', 'employee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_employee_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attendance_status'), ['attendance_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_employee_date'), ['employee_id', 'attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_employee'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_date'), ['attendance_date'], unique=False)

    # ### end Alembic commands ###
