"""Add attendance performance indexes

Revision ID: e4ee963a6f4c
Revises: d3d199411431
Create Date: 2025-09-22 18:33:33.795738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ee963a6f4c'
down_revision = 'd3d199411431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add performance indexes for attendance table
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_date', ['attendance_date'], unique=False)
        batch_op.create_index('idx_attendance_employee', ['employee_id'], unique=False)
        batch_op.create_index('idx_attendance_employee_date', ['employee_id', 'attendance_date'], unique=False)
        batch_op.create_index('idx_attendance_status', ['attendance_status'], unique=False)
        batch_op.create_index('idx_attendance_created_date', ['created_date'], unique=False)
        batch_op.create_index('idx_attendance_marked_by', ['marked_by'], unique=False)

    # Add performance indexes for employees table
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employee_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('idx_employee_site_id', ['site_id'], unique=False)
        batch_op.create_index('idx_employee_salary_code', ['salary_code'], unique=False)
        batch_op.create_index('idx_employee_department_id', ['department_id'], unique=False)

    # Add indexes for wage_master table (used in joins)
    with op.batch_alter_table('wage_master', schema=None) as batch_op:
        batch_op.create_index('idx_wage_master_salary_code', ['salary_code'], unique=False)
        batch_op.create_index('idx_wage_master_site_name', ['site_name'], unique=False)

    # Add indexes for sites table
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index('idx_sites_site_id', ['site_id'], unique=False)
        batch_op.create_index('idx_sites_site_name', ['site_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_employee_site_id'), ['site_id', 'employee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_employee_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attendance_status'), ['attendance_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_employee_date'), ['employee_id', 'attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_employee'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_date'), ['attendance_date'], unique=False)

    # ### end Alembic commands ###
