"""Add Form B performance indexes

Revision ID: f5a2b3c4d5e6
Revises: e4ee963a6f4c
Create Date: 2025-10-04 12:34:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a2b3c4d5e6'
down_revision = 'e4ee963a6f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add performance indexes for Form B bulk queries

    # Index for employee salary_code lookups (used in bulk employee queries)
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employee_salary_code', ['salary_code'], unique=False)

    # Index for wage_masters salary_code lookups (used in bulk wage queries)
    with op.batch_alter_table('wage_masters', schema=None) as batch_op:
        batch_op.create_index('idx_wage_master_salary_code', ['salary_code'], unique=False)
        batch_op.create_index('idx_wage_master_site_name', ['site_name'], unique=False)

    # Index for deductions bulk queries (employee_id filtering)
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.create_index('idx_deduction_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('idx_deduction_employee_active', ['employee_id', 'start_month'], unique=False)

    # Composite index for attendance bulk queries (already exists but ensure it's optimized)
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        # Ensure the composite index exists for bulk attendance queries
        batch_op.create_index('idx_attendance_employee_date_status', ['employee_id', 'attendance_date', 'attendance_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.drop_index('idx_deduction_employee_active')
        batch_op.drop_index('idx_deduction_employee_id')

    with op.batch_alter_table('wage_masters', schema=None) as batch_op:
        batch_op.drop_index('idx_wage_master_site_name')
        batch_op.drop_index('idx_wage_master_salary_code')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_salary_code')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_employee_date_status')

    # ### end Alembic commands ###