"""Add bulk upload performance indexes

Revision ID: f6a2b3c4d5e6
Revises: e17358e86af8
Create Date: 2025-10-13 12:06:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a2b3c4d5e6'
down_revision = 'e17358e86af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add composite indexes specifically for bulk attendance operations
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        # Index for bulk attendance queries by employee and date range
        batch_op.create_index('idx_attendance_employee_date_range', ['employee_id', 'attendance_date'], unique=False)

        # Index for monthly bulk operations
        batch_op.create_index('idx_attendance_month_year', [sa.text("EXTRACT(YEAR FROM attendance_date)"), sa.text("EXTRACT(MONTH FROM attendance_date)")], unique=False)

        # Index for bulk updates by marked_by and date range
        batch_op.create_index('idx_attendance_marked_by_date', ['marked_by', 'attendance_date'], unique=False)

    # Add indexes for employee lookups during bulk operations
    with op.batch_alter_table('employees', schema=None) as batch_op:
        # Composite index for employee lookups with salary code (used in site filtering)
        batch_op.create_index('idx_employee_salary_code_active', ['salary_code', 'employment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_salary_code_active')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_marked_by_date')
        batch_op.drop_index('idx_attendance_month_year')
        batch_op.drop_index('idx_attendance_employee_date_range')

    # ### end Alembic commands ###